language: bash

services:
  - docker

env:
  global:
    - LINT_IMAGE=lint

install:
  - docker build -t ${LINT_IMAGE} -f tests/Dockerfile .

script:
  - docker run --rm -ti --entrypoint terraform ${LINT_IMAGE} fmt -check=true -diff -recursive ./
  - |
    find . \
      -not -path '*/\.*' \
      -not -path './vendor/*' \
      # Pending Kubernetes Provider
      -not -path './modules/dashboard/*' \
      -type f -iname '*.tf' \
      -printf '%h\n' | sort | uniq | xargs -I{} bash -c "echo {} && docker run --rm ${LINT_IMAGE} {}"
branches:
  only:
  - master

notifications:
  email: false
