${fullname_override != "" ? "fullnameOverride: ${fullname_override}" : ""}

# For the full suite of supported values, see https://www.consul.io/docs/platform/k8s/helm.html
global:
  domain: ${consul_domain}
  image: ${image}
  imageK8S: ${image_k8s}
  datacenter: ${datacenter}

  # Gossip encryption key. To enable gossip encryption, provide the name of
  # a Kubernetes secret that contains a gossip key. You can create a gossip
  # key with the "consul keygen" command.
  # See https://www.consul.io/docs/commands/keygen.html
  gossipEncryption:
    secretName: ${gossip_secret}
    secretKey: ${gossip_key}

  # bootstrapACLs will automatically create and assign ACL tokens within
  # the Consul cluster. This currently requires enabling both servers and
  # clients within Kubernetes. Additionally requires Consul v1.4+ and
  # consul-k8s v0.8.0+.
  bootstrapACLs: false

server:
  replicas: ${server_replicas}
  bootstrapExpect: ${server_replicas}
  storage: ${server_storage}
  storageClass: ${server_storage_class}
  resources: ${server_resources}
  disruptionBudget:
    enabled: true
  extraConfig: ${server_extra_config}
  extraVolumes: ${server_extra_volumes}
  connect: ${connect_enable}
  affinity: ${server_affinity}
  tolerations: ${server_tolerations}
  priorityClassName: ${server_priority_class}
  annotations: ${server_annotations}

client:
  enabled: ${client_enabled}
  grpc: ${client_grpc} # Required for connect
  resources: ${client_resources}
  extraConfig: ${client_extra_config}
  extraVolumes: ${client_extra_volumes}
  tolerations: ${client_tolerations}
  priorityClassName: ${client_priority_class}
  annotations: ${client_annotations}

syncCatalog:
  enabled: ${enable_sync_catalog}
  default: ${sync_by_default}
  toConsul: ${sync_to_consul}
  toK8S: ${sync_to_k8s}
  k8sPrefix: ${sync_k8s_prefix}
  k8sTag: ${sync_k8s_tag}
  syncClusterIPServices: ${sync_cluster_ip_services}
  nodePortSyncType: ${sync_node_port_type}

ui:
  enabled: ${enable_ui}
  service:
    enabled: ${enable_ui}
    type: ${ui_service_type}
    annotations: ${ui_annotations}
    additionalSpec: ${ui_additional_spec}

connectInject:
  enabled: ${enable_connect_inject}
  default: ${connect_inject_by_default}
  namespaceSelector: ${connect_inject_namespace_selector}
  # certs:
  #     secretName: ""
  #     caBundle: ""
  #     certName: ""
  #     keyName: ""
