${fullname_override != "" ? "fullnameOverride: ${fullname_override}" : ""}

# For the full suite of supported values, see https://www.consul.io/docs/platform/k8s/helm.html
global:
  domain: ${consul_domain}
  image: ${image}
  imageK8S: ${image_k8s}
  datacenter: ${datacenter}
  enablePodSecurityPolicies: ${pod_security_policy_enable}

  # Gossip encryption key. To enable gossip encryption, provide the name of
  # a Kubernetes secret that contains a gossip key. You can create a gossip
  # key with the "consul keygen" command.
  # See https://www.consul.io/docs/commands/keygen.html
  gossipEncryption:
    secretName: ${gossip_secret}
    secretKey: ${gossip_key}

  # bootstrapACLs will automatically create and assign ACL tokens within
  # the Consul cluster. This currently requires enabling both servers and
  # clients within Kubernetes. Additionally requires Consul v1.4+ and
  # consul-k8s v0.8.0+.
  bootstrapACLs: false

  # Enables TLS encryption across the cluster to verify authenticity of the
  # servers and clients that connect. Note: It is HIGHLY recommended that you also
  # enable Gossip encryption.
  # See https://learn.hashicorp.com/consul/security-networking/agent-encryption
  #
  # Note: this relies on functionality introduced with Consul 1.4.1. Make sure
  # your global.image value is at least version 1.4.1.
  tls:
    enabled: ${tls_enabled}

    # serverAdditionalDNSSANs is a list of additional DNS names to
    # set as Subject Alternative Names (SANs) in the server certificate.
    # This is useful when you need to access the Consul server(s) externally,
    # for example, if you're using the UI.
    serverAdditionalDNSSANs: ${tls_server_additional_dns_sans}

    # serverAdditionalIPSANs is a list of additional IP addresses to
    # set as Subject Alternative Names (SANs) in the server certificate.
    # This is useful when you need to access Consul server(s) externally,
    # for example, if you're using the UI.
    serverAdditionalIPSANs: ${tls_server_additional_ip_sans}

    # If verify is true, 'verify_outgoing', 'verify_server_hostname', and
    # 'verify_incoming_rpc' will be set to true for Consul servers and clients.
    # Set this to false to incrementally roll out TLS on an existing Consul cluster.
    # Note: remember to switch it back to true once the rollout is complete.
    # Please see this guide for more details:
    # https://learn.hashicorp.com/consul/security-networking/certificates
    verify: ${tls_verify}

    # If httpsOnly is true, Consul will disable the HTTP port on both
    # clients and servers and only accept HTTPS connections.
    httpsOnly: ${tls_https_only}

server:
  replicas: ${server_replicas}
  bootstrapExpect: ${server_replicas}
  storage: ${server_storage}
  storageClass: ${server_storage_class}
  resources: ${server_resources}
  disruptionBudget:
    enabled: true
  extraConfig: ${server_extra_config}
  extraVolumes: ${server_extra_volumes}
  connect: ${connect_enable}
  affinity: ${server_affinity}
  tolerations: ${server_tolerations}
  priorityClassName: ${server_priority_class}
  annotations: ${server_annotations}

client:
  enabled: ${client_enabled}
  grpc: ${client_grpc} # Required for connect
  resources: ${client_resources}
  extraConfig: ${client_extra_config}
  extraVolumes: ${client_extra_volumes}
  tolerations: ${client_tolerations}
  priorityClassName: ${client_priority_class}
  annotations: ${client_annotations}

syncCatalog:
  enabled: ${enable_sync_catalog}
  default: ${sync_by_default}
  toConsul: ${sync_to_consul}
  toK8S: ${sync_to_k8s}
  k8sPrefix: ${sync_k8s_prefix}
  k8sTag: ${sync_k8s_tag}
  syncClusterIPServices: ${sync_cluster_ip_services}
  nodePortSyncType: ${sync_node_port_type}
  addK8SNamespaceSuffix: ${sync_add_k8s_namespace_suffix}
  affinity: ${sync_affinity}
  tolerations: ${sync_tolerations}

ui:
  enabled: ${enable_ui}
  service:
    enabled: ${enable_ui}
    type: ${ui_service_type}
    annotations: ${ui_annotations}
    additionalSpec: ${ui_additional_spec}

connectInject:
  enabled: ${enable_connect_inject}
  default: ${connect_inject_by_default}
  namespaceSelector: ${connect_inject_namespace_selector}
  affinity: ${connect_inject_affinity}
  tolerations: ${connect_inject_tolerations}
  # certs:
  #     secretName: ""
  #     caBundle: ""
  #     certName: ""
  #     keyName: ""
